### ISSUE TITLE
Password text box

### ISSUE THREAD

**Issue by BananaSoftwaree** [Wolfyxon/secure-loginsystem#1]
You know what, it still miss something.
```html
<!DOCTYPE html>
<html>
    <head>
        <title>Login</title>
    </head>
    <body>
        <center>
            <h1>Login</h1>
            <form method="post" action="/auth">
                <input type="text" name="login">
                <input type="password" name="password">
                <input type="submit" value="Submit">
            </form>

        </center>
    </body>
</html>
```
The above code is my modified version of login html code.
Replace text box type in password text box to "password" so it can hide password with dot like this:

![image](https://user-images.githubusercontent.com/93658686/149689358-9f397f3c-fa40-48a8-aa22-4bc5b6b6486c.png)

It will more secure lol
That is my suggestion, if you have any question, ask me in Discord.
Thanks.

**Comment by Wolfyxon** [comment]
Ok i"'ll change that

**Comment by Wolfyxon** [comment]
Done
